apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cronjob
spec:
  schedule: {{ .SCHEDULE }} 
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: helloworld
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "{{.message}} $(NAME)"
            env:
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: test-cronjob-cf
                  key: name
          restartPolicy: Never