apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cloudeng-sample-cron-job
spec:
  schedule: {{ .SCHEDULE }} 
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: helloworld
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo "{{.message}}"
          restartPolicy: Never