apiVersion: batch/v1
kind: Job
metadata:
  name: test-deployment
spec:
  template:
    spec:
      containers:
      - name: helloworld
        image: busybox
        args:
        - /bin/sh
        - -c
        - date
      restartPolicy: Never
  backoffLimit: 4